# Dockerfile for xxx environment

FROM aggresss/elementary:bionic

MAINTAINER aggresss <aggresss@163.com>
LABEL IMAGE=xxx/bionic VERSION=yyy

# configure environment for xxx
RUN apt-get update && apt-get install -y --no-install-recommends \
    \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* \
    && \
    echo "[program:xxxx]" > /etc/supervisor/conf.d/sshd.conf && \
    echo "command=/usr/sbin/xxxx" >> /etc/supervisor/conf.d/sshd.conf

EXPOSE XX
USER XX
WORKDIR XX

